#pragma once
#include <cstddef>

namespace ear {
  namespace points_file {
    // defined in autogenerated .cpp file from
    // resources/Design_5200_100_random.dat
    extern const double points[][2];
    extern const size_t num_points;
  }  // namespace points_file
}  // namespace ear
