name: Coverage

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        persist-credentials: false
    - name: Install dependencies (apt)
      run: |
        sudo apt-get install -y build-essential cmake ninja-build libboost-dev python-pip
    - name: Install dependencies (pip)
      run: |
        sudo pip install codecov
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Coverage -DBUILD_SHARED_LIBS=ON -DEAR_HIDE_INTERNAL_SYMBOLS=OFF
    - name: Build
      run: |
        cd build
        cmake --build .
    - name: Test
      run: |
        cd build
        ctest --output-on-failure
    - uses: codecov/codecov-action@v1
