name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        shared: [BUILD_SHARED_LIBS=True, BUILD_SHARED_LIBS=False]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        persist-credentials: false
    - name: Install dependencies (chocolatey)
      run: choco install ninja
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Configure
      run: |
        mkdir build
        cd build
        cmake .. -G Ninja -DBOOST_ROOT="$env:BOOST_ROOT_1_72_0" -DCMAKE_CXX_COMPILER="cl.exe" -DCMAKE_BUILD_TYPE=Release -D${{ matrix.shared }}
    - name: Build
      run: |
        cd build
        cmake --build .
    - name: Add library directory to PATH for Tests
      run: echo "${{ github.workspace }}\build\src" >> $GITHUB_PATH
    - name: Test
      run: |
        cd build
        ctest --output-on-failure
